rules:

  unpinned-uses:
    config:
      policies:
        actions/*: hash-pin
        github/*: hash-pin
        softprops/*: hash-pin
        astral-sh/*: hash-pin
        codecov/*: hash-pin

  forbidden-uses:
    config:
      allow:
        - actions/checkout
        - actions/cache
        - actions/github-script
        - actions/setup-python
        - github/codeql-action/upload-sarif
        - softprops/action-gh-release
        - astral-sh/setup-uv
        - codecov/codecov-action
