default_language_version:
  python: python3

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.3.1'
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
        - types-all
        - pydantic>=2.5.2,<3.0.0
        - types-openpyxl>=3.1.0.20240308
        - pandas-stubs>=2.2.0.240218
        - types-python-dateutil>=2.8.19.20240106"
        - types-requests>=2.31.0.20240218
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: no-commit-to-branch
        args: ['--branch', 'master']
      - id: pretty-format-json
        args: [--autofix]
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: fix-byte-order-marker
        exclude: .gitignore
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.2
    hooks:
      - id: poetry-check
      - id: poetry-lock
