repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.1'
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
  - repo: https://github.com/psf/black
    rev: 23.10.0
    hooks:
      - id: black
        language: system
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        additional_dependencies:
        - types-all
        - pydantic>=2.4.2
        - types-openpyxl>=3.1.0.24
        - pandas-stubs>=2.1.1.230928
        - types-python-dateutil>=2.8.19.14
        - types-requests>=2.31.0.10
        - types-toml>=0.10.8.7
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=auto]
  - repo: https://github.com/python-poetry/poetry
    rev: 1.6.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
