default_language_version:
  python: python3.14

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.7
    hooks:
      - id: uv-lock
        args: [ --check ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.5
    hooks:
      - id: ruff-check
        args: [ --fix, --exit-non-zero-on-fix ]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.1.0
    hooks:
      - id: mypy
        pass_filenames: false
        args:
          - --install-types
          - --non-interactive
          - --config-file=pyproject.toml
        additional_dependencies:
          - pandas-stubs>=2.1.2
          - pydantic>=2.5.2
          - scipy-stubs>=1.14.1.0
          - types-openpyxl>=3.1.2
          - types-python-dateutil>=2.8.2
          - types-requests>=2.20.0
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
        exclude: ^docs/build/|^docs/_build/
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: ^docs/build/|^docs/_build/|docs/source/api/generated/
      - id: name-tests-test
        args: [ --pytest-test-first ]
      - id: no-commit-to-branch
        args: [ '--branch', 'master' ]
      - id: pretty-format-json
        args: [ --autofix ]
      - id: trailing-whitespace
        exclude: ^docs/build/|^docs/_build/|docs/source/api/generated/
      - id: mixed-line-ending
        args: [ --fix=auto ]
        exclude: ^docs/build/|^docs/_build/|docs/source/api/generated/
      - id: fix-byte-order-marker
        exclude: ^docs/build/|^docs/_build/|docs/source/api/generated/
  - repo: local
    hooks:
      - id: zizmor
        name: zizmor
        entry: scripts/run-zizmor.sh
        language: system
        require_serial: true
        pass_filenames: false
        files: (\.github/(workflows/.*|dependabot\.ya?ml|zizmor\.yml))|(action\.ya?ml)$
        args: [--strict-collection, --pedantic, .]
