[tool.poetry]
name = "openseries"
version = "1.1.3"
description = "Package for simple financial time series analysis."
authors = ["Martin Karrin <martin.karrin@captor.se>"]
homepage = "https://github.com/CaptorAB/OpenSeries"
repository = "https://github.com/CaptorAB/OpenSeries"
license = "BSD-3-Clause"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: BSD License",
    "Intended Audience :: Financial and Insurance Industry",
    "Topic :: Office/Business :: Financial :: Investment",
    "Natural Language :: English",
    "Development Status :: 5 - Production/Stable",
    "Operating System :: OS Independent",
    "Framework :: Pydantic",
]
keywords = [
    "python",
    "python3",
    "plotly",
    "pandas",
    "finance",
    "fintech",
    "data-science",
    "timeseries",
    "timeseries-data",
    "timeseries-analysis",
    "investment",
    "investment-analysis",
    "investing"
]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
ffn = "^0.3.7"
holidays = "^0.18"
numpy = "^1.25.1"
openpyxl = "^3.1.2"
pandas = "^2.0.3"
plotly = "^5.15.0"
pydantic = "^2.1.1"
python-dateutil = "^2.8.2"
python-stdnum = "^1.18"
scipy = "^1.11.1"
statsmodels = "^0.14.0"

[tool.poetry.group.dev.dependencies]
black = "23.7.0"
coverage = {extras = ["toml"], version = "^7.2.7"}
coverage-badge = "^1.1.0"
flake8 = "^6.1.0"
flake8-black = "^0.3.6"
flake8-pyproject = "^1.2.3"
mypy = "^1.4.1"
pre-commit = "^3.3.3"
pylint = "^2.17.4"
pytest = "^7.4.0"
pytest-split = "^0.8.1"
toml = "^0.10.2"
types-python-dateutil = "^2.8.19.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[poetry.virtualenvs]
in-project = true
path = "venv"

[poetry.virtualenvs.options]
no-pip = true
no-setuptools = true

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore::DeprecationWarning:pandas_datareader.*:"
]

[tool.black]
line-length = 87

[tool.coverage.run]
omit = ["venv/*"]
include = ["openseries/*"]

[tool.coverage.report]
skip_empty = true
fail_under = 99

[tool.mypy]
strict = true
ignore_missing_imports = true
warn_redundant_casts = true
disable_error_code = ["valid-type"]
exclude = ["venv/*"]

[tool.pylint]
disable = ["C2801", "E0213", "R0801"]
max-line-length = 87
max-module-lines=3380
min-public-methods=0
max-public-methods=89
max-statements=51
max-branches=22
max-locals=29
max-args=12
output-format = "colorized"
ignore-patterns= "\\w+\\.json$"

[tool.pylint."MESSAGES CONTROL"]
extension-pkg-whitelist = "pydantic"

[tool.flake8]
max-line-length = 87
filename = "/openseries/*.py,/tests/*.py"
exclude = "venv,github,git"
extend-ignore = ["C901", "E203", "F722", "F821", "W503"]
format = "pylint"
hang-closing = false
doctests = true
verbose = true
show-source = true
color = "auto"
