[tool.poetry]
name = "openseries"
version = "1.3.5"
description = "Package for simple financial time series analysis."
authors = ["Martin Karrin <martin.karrin@captor.se>"]
repository = "https://github.com/CaptorAB/OpenSeries"
license = "BSD-3-Clause"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: BSD License",
    "Intended Audience :: Financial and Insurance Industry",
    "Topic :: Office/Business :: Financial :: Investment",
    "Natural Language :: English",
    "Development Status :: 5 - Production/Stable",
    "Operating System :: OS Independent",
    "Framework :: Pydantic",
]
keywords = [
    "python",
    "finance",
    "fintech",
    "data-science",
    "timeseries",
    "timeseries-data",
    "timeseries-analysis",
    "investment",
    "investment-analysis",
    "investing"
]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
ffn = "^0.3.7"
holidays = "^0.33"
numpy = "^1.25.2"
openpyxl = "^3.1.2"
pandas = "^2.0.3"
plotly = "^5.17.0"
pydantic = "^2.4.2"
python-dateutil = "^2.8.2"
scipy = "^1.11.2"
statsmodels = "^0.14.0"

[tool.poetry.group.dev.dependencies]
black = "23.9.1"
coverage = {extras = ["toml"], version = "^7.3.1"}
coverage-badge = "^1.1.0"
mypy = "^1.5.1"
pre-commit = "^3.4.0"
pytest = "^7.4.2"
ruff = "^0.0.291"
toml = "^0.10.2"
# This import takes care of single mypy import error on dateutil in datefixer.py
types-python-dateutil = "^2.8.19.14"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.setuptools_scm]

[poetry.virtualenvs]
in-project = true
path = "venv"

[poetry.virtualenvs.options]
no-pip = true

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore:The default fill_method:FutureWarning::",
    # https://github.com/pydata/pandas-datareader/issues/960
    "ignore::DeprecationWarning:pandas_datareader.*:"
]

[tool.black]
line-length = 87

[tool.coverage.run]
omit = ["venv/*"]
include = ["openseries/*"]

[tool.coverage.report]
skip_empty = true
fail_under = 99

[tool.mypy]
strict = true
ignore_missing_imports = true
warn_redundant_casts = true
exclude = ["venv/*"]
plugins = ["pydantic.mypy"]

[tool.ruff]
select = ["ALL"]
ignore = ["D211", "D212", "TCH"]
fixable = ["ALL"]
line-length = 87

[tool.ruff.pylint]
max-args = 12
max-branches = 22
max-statements = 54

[tool.ruff.pyupgrade]
keep-runtime-typing = true
