[tool.poetry]
name = "openseries"
version = "0.10.8"
description = "Package for simple financial time series analysis."
authors = ["Martin Karrin <martin.karrin@captor.se>"]
license = "BSD-3-Clause"
readme = "README.md"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project.urls]
repository = "https://github.com/CaptorAB/OpenSeries"

classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: BSD License",
    "Intended Audience :: Financial and Insurance Industry",
    "Topic :: Office/Business :: Financial :: Investment",
    "Natural Language :: English",
    "Development Status :: 5 - Production/Stable",
    "Operating System :: OS Independent",
]

keywords = [
    "python",
    "python3",
    "plotly",
    "pandas",
    "finance",
    "fintech",
    "data-science",
    "timeseries",
    "timeseries-data",
    "timeseries-analysis",
    "investment",
    "investment-analysis",
    "investing"
]

[tool.poetry.dependencies]
python = "^3.10"
holidays = "^0.18"
numpy = "^1.24.1"
pandas = "^1.5.2"
plotly = "^5.11.0"
python-dateutil = "^2.8.2"
python-stdnum = "^1.18"
requests = "^2.28.1"
scipy = "^1.9.3"
statsmodels = "^0.13.5"
pydantic = "^1.10.5"

[tool.poetry.group.test.dependencies]
coverage = "*"
pytest = "*"
pytest-split = "*"

[tool.poetry.group.coverage.dependencies]
coverage = "*"

[tool.poetry.group.dev.dependencies]
black = "23.1.0"
coverage = "*"
flake8 = "6.0.0"
flake8-black = "*"
pre-commit = "*"
pytest = "*"

[tool.black]
line-length = 88
