[tool.poetry]
name = "openseries"
version = "0.12.1"
description = "Package for simple financial time series analysis."
authors = ["Martin Karrin <martin.karrin@captor.se>"]
homepage = "https://github.com/CaptorAB/OpenSeries"
repository = "https://github.com/CaptorAB/OpenSeries"
license = "BSD-3-Clause"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: BSD License",
    "Intended Audience :: Financial and Insurance Industry",
    "Topic :: Office/Business :: Financial :: Investment",
    "Natural Language :: English",
    "Development Status :: 5 - Production/Stable",
    "Operating System :: OS Independent",
    "Framework :: Pydantic",
]
keywords = [
    "python",
    "python3",
    "plotly",
    "pandas",
    "finance",
    "fintech",
    "data-science",
    "timeseries",
    "timeseries-data",
    "timeseries-analysis",
    "investment",
    "investment-analysis",
    "investing"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
holidays = "^0.18"
numpy = "^1.24.1"
pandas = "^1.5.2"
plotly = "^5.11.0"
pydantic = "^1.10.5"
python-dateutil = "^2.8.2"
python-stdnum = "^1.18"
requests = "^2.28.1"
scipy = "^1.9.3"
statsmodels = "^0.13.5"
types-python-dateutil = "^2.8.19.11"
pylint = "^2.17.2"

[tool.poetry.group.dev.dependencies]
black = "23.1.0"
coverage = {extras = ["toml"], version = "^7.2.2"}
coverage-badge = "^1.1.0"
flake8 = "6.0.0"
flake8-black = "^0.3.6"
mypy = "^1.1.1"
poetry = "1.4.0"
pre-commit = "^3.2.0"
pytest = "^7.2.2"
pytest-split = "^0.8.0"

[tool.black]
line-length = 88

[tool.mypy]
strict = true
ignore_missing_imports = true
warn_redundant_casts = true
disable_error_code = ["valid-type"]
exclude = ["venv/*", ".venv"]

[tool.coverage.run]
omit = ["venv/*", ".venv"]
include = ["openseries/*"]

[tool.coverage.report]
skip_empty = true
fail_under = 99

[tool.pylint]
disable = "C0114, R0913, R0903, R0904, C2801"
ignore = ["venv/*", ".venv"]
max-line-length = 88
output-format = "colorized"

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"
