[tool.poetry]
name = "openseries"
version = "0.13.0"
description = "Package for simple financial time series analysis."
authors = ["Martin Karrin <martin.karrin@captor.se>"]
homepage = "https://github.com/CaptorAB/OpenSeries"
repository = "https://github.com/CaptorAB/OpenSeries"
license = "BSD-3-Clause"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: BSD License",
    "Intended Audience :: Financial and Insurance Industry",
    "Topic :: Office/Business :: Financial :: Investment",
    "Natural Language :: English",
    "Development Status :: 5 - Production/Stable",
    "Operating System :: OS Independent",
    "Framework :: Pydantic",
]
keywords = [
    "python",
    "python3",
    "plotly",
    "pandas",
    "finance",
    "fintech",
    "data-science",
    "timeseries",
    "timeseries-data",
    "timeseries-analysis",
    "investment",
    "investment-analysis",
    "investing"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
holidays = "^0.18"
numpy = "^1.24.1"
pandas = "^1.5.2"
plotly = "^5.11.0"
pydantic = "^1.10.5"
python-dateutil = "^2.8.2"
python-stdnum = "^1.18"
requests = "^2.28.1"
scipy = "^1.9.3"
statsmodels = "^0.13.5"
urllib3 = ">=1.26.9,<2.0.0"
ffn = "0.3.6"

[tool.poetry.group.dev.dependencies]
black = "23.3.0"
coverage = {extras = ["toml"], version = "^7.2.2"}
coverage-badge = "^1.1.0"
flake8 = "6.0.0"
flake8-black = "^0.3.6"
flake8-pyproject = "^1.2.3"
mypy = "^1.1.1"
pre-commit = "^3.2.0"
pylint = "^2.17.2"
pytest = "^7.2.2"
pytest-split = "^0.8.0"
types-python-dateutil = "^2.8.19.12"

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore::DeprecationWarning:ffn.*:",
    "ignore::DeprecationWarning:pandas_datareader.*:"
]

[tool.black]
line-length = 87

[tool.coverage.run]
omit = ["venv/*"]
include = ["openseries/*"]

[tool.coverage.report]
skip_empty = true
fail_under = 99

[tool.mypy]
strict = true
ignore_missing_imports = true
warn_redundant_casts = true
disable_error_code = ["valid-type"]
exclude = ["venv/*"]

[tool.pylint]
disable = ["C2801", "E0213", "R0801"]
max-line-length = 87
max-module-lines=3350
min-public-methods=0
max-public-methods=88
max-statements=51
max-branches=22
max-locals=29
max-args=12
output-format = "colorized"
ignore-patterns= "\\w+\\.json$"

[tool.pylint."MESSAGES CONTROL"]
extension-pkg-whitelist = "pydantic"

[tool.flake8]
max-line-length = 87
filename = "/openseries/*.py,/tests/*.py"
exclude = "venv,github,git"
extend-ignore = ["C901", "E203", "F722", "F821", "W503"]
format = "pylint"
hang-closing = false
doctests = true
verbose = true
show-source = true
color = "auto"
