[tool.poetry]
name = "openseries"
version = "1.2.2"
description = "Package for simple financial time series analysis."
authors = ["Martin Karrin <martin.karrin@captor.se>"]
repository = "https://github.com/CaptorAB/OpenSeries"
license = "BSD-3-Clause"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: BSD License",
    "Intended Audience :: Financial and Insurance Industry",
    "Topic :: Office/Business :: Financial :: Investment",
    "Natural Language :: English",
    "Development Status :: 5 - Production/Stable",
    "Operating System :: OS Independent",
    "Framework :: Pydantic",
]
keywords = [
    "python",
    "finance",
    "fintech",
    "data-science",
    "timeseries",
    "timeseries-data",
    "timeseries-analysis",
    "investment",
    "investment-analysis",
    "investing"
]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
ffn = "^0.3.7"
holidays = "^0.30"
numpy = "^1.25.2"
openpyxl = "^3.1.2"
pandas = "^2.0.3"
plotly = "^5.16.0"
pydantic = "^2.2.1"
python-dateutil = "^2.8.2"
python-stdnum = "^1.19"
scipy = "^1.11.2"
statsmodels = "^0.14.0"

[tool.poetry.group.dev.dependencies]
black = "23.7.0"
coverage = {extras = ["toml"], version = "^7.3.0"}
coverage-badge = "^1.1.0"
mypy = "^1.5.1"
pre-commit = "^3.3.3"
pytest = "^7.4.0"
pytest-split = "^0.8.1"
ruff = "^0.0.285"
toml = "^0.10.2"
# This import takes care of single mypy import error on dateutil in datefixer.py
types-python-dateutil = "^2.8.19.14"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[poetry.virtualenvs]
in-project = true
path = "venv"

[poetry.virtualenvs.options]
no-pip = true
no-setuptools = true

[tool.pytest.ini_options]
# https://github.com/pydata/pandas-datareader/issues/960
filterwarnings = ["error", "ignore::DeprecationWarning:pandas_datareader.*:"]

[tool.black]
line-length = 87

[tool.coverage.run]
omit = ["venv/*"]
include = ["openseries/*"]

[tool.coverage.report]
skip_empty = true
fail_under = 99

[tool.mypy]
strict = true
ignore_missing_imports = true
warn_redundant_casts = true
disable_error_code = ["misc"]
exclude = ["venv/*"]

[tool.ruff]
select = [
    "A",
    "ANN",
    "B",
    "COM",
    "DTZ",
    "E",
    "F",
    "I",
    "N",
    "PD",
    "RUF",
    "TID",
    "UP",
    "W"
]
ignore = ["ANN401", "E501", "D"]
fixable = ["ALL"]
unfixable = []
exclude = [
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "venv",
]
per-file-ignores = {}
line-length = 87
