version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo
    environment:
        SETUPTOOLS_USE_DISTUTILS: stdlib #https://stackoverflow.com/questions/63663362/django-python3-on-install-i-get-parent-module-setuptools-not-loaded

    steps:
      - checkout
      - run: python3 -m venv ./venv
      - run: PYTHONPATH=${PWD} ./venv/bin/pip3 install --upgrade -r requirements.txt      
      - run: PYTHONPATH=${PWD} ./venv/bin/nosetests -vv --nologcapture --nocapture  ./
      - run: PYTHONPATH=${PWD} ./venv/bin/coverage report openseries/*.py
      - slack/status:
        webhook: webhook

orbs:
        slack: circleci/slack@3.4.2
