version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          name: Linux kernel version
          command: cat /proc/version
      - run:
          name: Install Python in a virtual environment
          command: python3 -m venv venv
      - run:
          name: Activate environment
          command: ./venv/bin/activate
      - run:
          name: Check Python version
          command: |
            python --version
            whereis python
      - run:
          name: Upgrade pip and check version
          command: |
            pip install --upgrade pip
            pip --version
      - run:
          name: Install dependencies from requirements.txt
          command: pip install -r requirements.txt
      - run:
          name: Check formatting with black
          command: black ./
      - run:
          name: Tests with pytest
          command: coverage run -m pytest --verbose ./
      - run:
          name: Report coverage
          command: coverage report

workflows:
  version: 2
  build-master:
    jobs:
      - build
