version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Switch timezone to Stockholm
          command: sudo cp /usr/share/zoneinfo/Europe/Stockholm /etc/localtime
      - run:
          name: Create Python venv environment
          command: |
            python3 -m venv ./venv
      - run:
          name: Check Python version
          command: |
            venv/bin/python3 --version
      - run:
          name: Update pip
          command: |
            venv/bin/pip3 install --upgrade "pip==21.3.1"
      - run:
          name: Check Pip version
          command: |
            venv/bin/pip3 --version
      - run:
          name: Install dependencies
          command: |
            venv/bin/pip3 install --upgrade -r requirements.txt
      - run:
          name: Run tests
          command: |
            venv/bin/nosetests -v --nologcapture --nocapture --with-timer ./
      - slack/status:
        webhook: webhook

orbs:
        slack: circleci/slack@3.4.2
