version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo
    steps:
      - checkout
      - run: python3 -m venv ./venv
      - run:
          name: Switch timezone to Stockholm
          command: sudo cp /usr/share/zoneinfo/Europe/Stockholm /etc/localtime
      - run: python3 --version
      - run: sudo pip install --upgrade "pip==21.3.1"
      - run: pip --version
      - run:
          name: Install dependencies
          command: |
            sudo pip3 install --upgrade -r requirements.txt
      - run:
          name: Run tests
          command: |
            PYTHONPATH=${PWD} ./venv/bin/nosetests -vv --nologcapture --nocapture --with-timer ./
      - slack/status:
        webhook: webhook

orbs:
        slack: circleci/slack@3.4.2