version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          name: Install python in a virtual environment and activate it
          command: |
            python3 -m venv venv
            . venv/bin/activate
      - run:
          name: Upgrade pip
          command: |
            . venv/bin/activate
            pip install --upgrade pip
            pip --version
      - run:
          name: Install dependencies from requirements.txt
          command: |
            . venv/bin/activate
            pip install -r requirements.txt
            python --version
      - run:
          name: Tests with pytest and coverage
          command: |
            . venv/bin/activate
            coverage run -m pytest --verbose ./
            coverage report

workflows:
  version: 2
  build-master:
    jobs:
      - build
