version: 2.1

orbs:
  python: circleci/python@2.0.3

executors:
  docker:
    docker:
      - image: cimg/python:3.10.4

jobs:
  test:
    working_directory: ~/repo
    parameters:
      os:
        type: executor
    executor: << parameters.os >>

    steps:
      - checkout
      - run:
          name: Linux kernel version
          command: cat /proc/version
      - run:
          name: Install Python in a virtual environment
          command: python3 -m venv venv
      - run:
          name: Check Python version
          command: |
            . venv/bin/activate
            python --version
            which python
      - run:
          name: Upgrade pip and check version
          command: |
            . venv/bin/activate
            pip install --upgrade pip
            pip --version
      - run:
          name: Install dependencies from requirements.txt
          command: |
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Tests with pytest
          command: |
            . venv/bin/activate
            PYTHONPATH=${PWD} coverage run -m pytest --verbose
      - run:
          name: Report coverage
          command: |
            . venv/bin/activate
            PYTHONPATH=${PWD} coverage report

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              os: [docker]