version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Switch timezone to Stockholm
          command: sudo cp /usr/share/zoneinfo/Europe/Stockholm /etc/localtime
      - run: python3 --version
      - run: python3 -m venv ./venv
      - run: sudo ./venv/bin/activate
      - run: venv/bin/pip install --upgrade "pip==21.3.1"
      - run: venv/bin/pip --version
      - run:
          name: Install dependencies
          command: |
            venv/bin/pip install --upgrade -r requirements.txt
      - run:
          name: Run tests
          command: |
            PYTHONPATH=${PWD} venv/bin/nosetests -vv --nologcapture --nocapture --with-timer ./
      - run: sudo ./venv/bin/deactivate
