version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.10

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Switch timezone to Stockholm
          command: sudo cp /usr/share/zoneinfo/Europe/Stockholm /etc/localtime
      - run: python --version
      - run: pip --version
      - run: pip install --upgrade -r requirements.txt
      - run: PYTHONPATH=${PWD} pytest --verbose
