version: 2.1
executors:
  py36-executor:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.1

jobs:
  build:
    executor: py36-executor
    steps:
      - checkout
      - run:
          name: Switch timezone to Stockholm
          command: sudo cp /usr/share/zoneinfo/Europe/Stockholm /etc/localtime
      - run:
          name: Update pip
          command: |
            pip3 install --user --upgrade "pip==21.3.1"
      - run:
          name: Check Pip version
          command: |
            pip --version
      - run:
          name: Create Python pipenv environment
          command: |
            sudo pip install pipenv
      - run:
          name: Check Python version
          command: |
            pipenv --py
      - run:
          name: Install dependencies
          command: |
            pipenv install
      - run:
          name: Run tests
          command: |
            pipenv run bin/nosetests -v --nologcapture --nocapture --with-timer ./
      - slack/status:
        webhook: webhook

orbs:
        slack: circleci/slack@3.4.2
