version: 2.1
orbs:
        slack: circleci/slack@4.5.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo
    environment:
        SETUPTOOLS_USE_DISTUTILS: stdlib #https://stackoverflow.com/questions/63663362/django-python3-on-install-i-get-parent-module-setuptools-not-loaded

    steps:
      - checkout
      - run: python3 -m venv ./venv
      - run:
          name: Install dependencies
          command: |
            PYTHONPATH=${PWD} ./venv/bin/pip3 install --upgrade -r requirements.txt
      - run:
          name: Run tests
          command: |
            PYTHONPATH=${PWD} ./venv/bin/nosetests -vv --nologcapture --nocapture --with-timer ./
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1