name: "Install Environment and Dependencies"
description: "Install environment, loads cached venv and install dependencies"

inputs:
  cache_version:
    description: 'Value gets appended to the cache key and will invalidate the cache if it changes'
    required: true
  poetry_group:
    description: 'Controlling which poetry group to install from'
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      id: py
      with:
        python-version-file: '.python-version'

    - name: Use GNU tar
      shell: cmd
      run: |
        echo "Adding GNU tar to PATH"
        echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"
      if: ${{ runner.os == 'windows-latest' }}

    - name: Read file contents
      shell: bash
      run: |
        my_file_contents=$(cat "$GITHUB_WORKSPACE/.python-version")
        echo "$my_file_contents"

    - name: Write cache version
      shell: bash
      run: echo $CACHE_VERSION >> cache_version
      env:
        CACHE_VERSION: ${{ inputs.cache_version }}

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: |
          .venv
          poetry-lock
        key: venv-${{ runner.os }}-python-${{ steps.py.outputs.python-version }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('cache_version') }}

    - name: Install and configure Poetry
      shell: bash
      run: |
        python -m pip install poetry==1.3.2
        python -m poetry config virtualenvs.in-project true

    - name: Install Project
      shell: bash
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install ${{ inputs.poetry_group }}
