name: "Install Environment"
description: "Install environment, loads cached venv if applicable, and performs
miscellaneous other operations"

inputs:
  cache_version:
    description: 'Value gets appended to the cache key and will therefore invalidate the cache if it changes'
    required: true
  python-version:
    description: 'Python version'
    type: string
    required: true
  os:
    description: 'OS'
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Delete error-causing bash
      shell: bash
      if: ${{ inputs.os == 'windows-latest' }}
      run: rm.exe "C:/WINDOWS/system32/bash.EXE"

    - name: Set path to bash for example runner
      shell: bash
      if: ${{ inputs.os == 'windows-latest' }}
      run: |
        echo "SHELL_EXECUTABLE=C:\Program Files\Git\bin\bash.exe" >> $GITHUB_ENV

    - name: Get current date
      shell: bash
      id: date
      run: echo "date=$(date +'calendar-week-%W')" >> $GITHUB_OUTPUT

    - name: Write cache version
      shell: bash
      run: echo $CACHE_VERSION >> cache_version
      env:
        CACHE_VERSION: ${{inputs.cache_version}}

    - name: Load cached venv
      id: cached-virtualenv
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-python-${{ inputs.python-version }}-${{ hashFiles('pyproject.toml') }}-${{ steps.date.outputs.date }}-${{ hashFiles('cache_version') }}

    - name: Set virtualenv activation script env variable (windows)
      shell: bash
      run: echo "VENV=.venv/scripts/activate" >> "$GITHUB_ENV"
      if: runner.os == 'Windows'

    - name: Set virtualenv activation script env variable (unix)
      shell: bash
      run: echo "VENV=.venv/bin/activate" >> "$GITHUB_ENV"
      if: runner.os != 'Windows'

    - name: Install Project
      shell: bash
      if: steps.cached-virtualenv.outputs.cache-hit != 'true'
      run: |
        python -m venv .venv
        source $VENV
        python -m pip install --upgrade pip
        python -m pip install poetry==1.3.2
