name: 'Install Environment and Dependencies'
description: 'Install environment, loads cached venv and install dependencies'

inputs:
  python_version:
    description: 'Python version from matrix or file'
    type: string
    required: true
  poetry_group:
    description: 'Controlling which poetry group to install from'
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      id: py
      with:
        python-version: ${{ inputs.python_version }}

    - name: Write cache version
      shell: bash
      run: echo $CACHE_VERSION >> cache_version
      env:
        CACHE_VERSION: ${{ inputs.cache_version }}

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: |
          .venv
          poetry-lock
        key: venv-${{ runner.os }}-python-${{ steps.py.outputs.python-version }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('cache_version') }}
        restore-keys: |
          venv-${{ runner.os }}-python-${{ steps.py.outputs.python-version }}-${{ hashFiles('pyproject.toml') }}-

    - name: Install Poetry and dependencies
      shell: bash
      run: |
        python -m pip install poetry==1.3.2
        poetry install ${{ inputs.poetry_group }}
        poetry config --list

    - name: Save dependencies to cache
      uses: actions/cache/save@v3
      with:
        path: |
          .venv
          poetry.lock
        key: venv-${{ runner.os }}-python-${{ steps.py.outputs.python-version }}-poetry_lock-${{ hashFiles('**/poetry.lock') }}-github_run_id-${{ github.run_id }}
