name: 'Install Environment and Dependencies'
description: 'Install environment, loads cached venv and install dependencies'

inputs:
  poetry_arg:
    description: 'Controlling which poetry group to install from'
    type: string

runs:
  using: 'composite'
  steps:
    - name: Check out GitHub repository ${{ github.repository }}
      uses: actions/checkout@v3

    - name: Set up Python on ${{ runner.os }}
      uses: actions/setup-python@v4
      id: setup_python
      with:
        python-version-file: '.python-version'

    - name: Cache virtualenv
      uses: actions/cache@v3
      id: cache_venv
      with:
        path: |
          ${{ env.pythonLocation }}
          ~/.local
        key: venv-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies on Python ${{ steps.setup_python.outputs.python-version }}
      shell: bash
      if: steps.cache_venv.outputs.cache-hit != 'true'
      run: |
        python -m pip install poetry==1.3.2
        python -m poetry config virtualenvs.in-project true
        poetry install --no-root ${{ inputs.poetry_arg }}
