name: 'Install Environment and Dependencies'
description: 'Install environment, loads cached venv and install dependencies'

inputs:
  cache_version:
    description: 'Value gets appended to the cache key and will invalidate the cache if it changes'
    required: true
  python_version:
    description: 'Python version from matrix or file'
    type: string
    required: true
  poetry_group:
    description: 'Controlling which poetry group to install from'
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      id: py
      with:
        python-version: ${{ inputs.python_version }}
        cache: 'poetry'

    - name: Install and configure Poetry
      shell: bash
      run: |
        python -m pip install poetry==1.3.2
        poetry config virtualenvs.in-project true
        poetry config virtualenvs.options.no-pip true
        poetry config virtualenvs.options.no-setuptools true

    - name: Install Dependencies. From cache if it matches
      shell: bash
      if: steps.py.cache-hit != 'true'
      run: poetry install ${{ inputs.poetry_group }}
