name: 'Install Environment and Dependencies'
description: 'Install environment, loads cached venv and install dependencies'

inputs:
  cache_version:
    description: 'Value gets appended to the cache key and will invalidate the cache if it changes'
    required: true
  python_version:
    description: 'Python version from matrix or file'
    type: string
    required: true
  poetry_group:
    description: 'Controlling which poetry group to install from'
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      id: py
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install Poetry and dependencies
      shell: bash
      run: |
        python -m pip install poetry==1.3.2
        poetry install ${{ inputs.poetry_group }}
        poetry config --list

    - name: Get Poetry cache-dir
      shell: bash
      id: poetry-cache
      run: |
        echo "dir=$(poetry config cache-dir)" >> $GITHUB_OUTPUT

    - name: Save dependencies to cache
      uses: actions/cache/save@v3
      with:
        path: |
          .venv
          ${{ steps.poetry-cache.outputs.dir }}
          poetry.lock
        key: venv-${{ runner.os }}-python-${{ steps.py.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
