package:
  name: openseries
  version: 1.4.7

requirements:
  host:
    - python
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<3.12.0
    - ffn >=1.0.0,<2.0.0
    - holidays >=0.37.0,<1.0.0
    - numpy >=1.23.2,<=1.26.0
    - openpyxl >=3.1.2,<4.0.0
    - pandas >=2.1.2,<3.0.0
    - plotly >=5.18.0,<6.0.0
    - pydantic >=2.5.1,<3.0.0
    - python-dateutil >=2.8.2,<3.0.0
    - scipy >=1.11.3,<2.0.0
    - statsmodels >=0.14.0,<0.15.0

test:
  imports:
    - openseries

about:
  home: https://github.com/CaptorAB/OpenSeries
  summary: Package for analyzing financial timeseries.
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - karrmagadgeteer2
