name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: ["3.10.4"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install -e .[dev]
        python -m pip install -U wheel twine setuptools

    - name: Fix
      run: python -m black ./

    - name: Lint
      run: python -m flake8 ./

    - name: Tests with Pytest
      run: coverage run -m pytest --verbose

    - name: Report coverage
      run: coverage report

    - name: Package and check
      run: |
        python setup.py sdist bdist_wheel
        python -m twine check dist/*
