name: Build

on: workflow_dispatch

env:
  POETRY_VER: 1.4.2

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        python-version: [ '3.10', '3.11' ]

    steps:
      - name: Check out GitHub repository ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Set up Python on ${{ runner.os }}
        uses: actions/setup-python@v4
        id: setup_python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load cached $HOME/.local
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: dotlocal-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('.github/workflows/build.yml') }}

      - name: Install Poetry ${{ env.POETRY_VER }} on Python ${{ steps.setup_python.outputs.python-version }}
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VER }}

      - name: Load cached venv
        id: cached_venv
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('.github/workflows/build.yml') }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies on Python ${{ steps.setup_python.outputs.python-version }}
        shell: bash
        if: steps.cached_venv.outputs.cache-hit != 'true'
        run: |
          poetry config virtualenvs.prefer-active-python true
          poetry install --no-root --with dev

      - name: Format with Black
        shell: bash
        run: poetry run black ./openseries/*.py ./tests/*.py

      - name: Check with Flake8
        shell: bash
        run: poetry run flake8

      - name: Type check with Mypy
        shell: bash
        run: poetry run mypy .

      - name: Lint check with Pylint
        shell: bash
        run: poetry run pylint ./openseries/* ./tests/*

      - name: Tests with Pytest
        shell: bash
        run: poetry run coverage run -m pytest --verbose --durations=20 --durations-min=2.0

      - name: Report coverage
        shell: bash
        run: poetry run coverage report

      - name: Package and check
        shell: bash
        run: |
          poetry build
          poetry check
