name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ~/repo

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: ["3.10.4"]

    steps:
    - name: Check out GitHub repository ${{ github.repository }}
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install -e .[dev]
        python -m pip install -U wheel twine setuptools

    - name: Tests with Pytest
      run: coverage run -m pytest --verbose

    - name: Report coverage
      run: coverage report

    - name: Package and check
      run: |
        python setup.py sdist bdist_wheel
        python -m twine check dist/*
