name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10' ]
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    steps:
      - name: Check out GitHub repository ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Setup environment with Python ${{ matrix.python-version }}
        uses: ./.github/actions/setup_environment
        with:
          cache_version: ${{ secrets.GH_ACTIONS_CACHE_KEY }}
          python_version: ${{ matrix.python-version }}
          poetry_group: --with test

      - name: Tests with Pytest
        run: poetry run coverage run -m pytest --verbose --durations=20 --durations-min=2.0

      - name: Report coverage
        run: poetry run coverage report

      - name: Package and check
        run: |
          poetry build
          poetry check
