name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10' ]
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    steps:
      - name: Check out GitHub repository ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup_build
        with:
          poetry_arg: --with test

      - name: Tests with Pytest
        shell: bash
        run: PYTHONPATH=${PWD} poetry run coverage run -m pytest --verbose --durations=20 --durations-min=2.0

      - name: Report coverage
        shell: bash
        run: PYTHONPATH=${PWD} poetry run coverage report

      - name: Package and check
        shell: bash
        run: |
          PYTHONPATH=${PWD} poetry build
          PYTHONPATH=${PWD} poetry check
