name: checks

on:
  workflow_dispatch:
  push:
    branches:
      - "*" # matches every branch that doesn't contain a '/'
      - "*/*" # matches every branch containing a single '/'
      - "**" # matches every branch

jobs:
  run_checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out GitHub repository ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pip install poetry==1.8.3

      - name: Set up Python on ${{ runner.os }}
        uses: actions/setup-python@v5
        id: setup_python
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Install dependencies on Python ${{ steps.setup_python.outputs.python-version }}
        run: poetry install --with dev

      - name: Check and fix with Ruff
        run: poetry run ruff check ./tests/*.py ./openseries/*.py --fix --exit-non-zero-on-fix

      - name: Type check with Mypy
        run: poetry run mypy .
