name: Download and report coverage

on:
  workflow_dispatch:
  workflow_call:

jobs:
  coverage:
    name: coverage
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        group: [ 1, 2, 3, 4, 5 ]
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        python-version: [ '3.10' ]
      fail-fast: false

    steps:
      - name: Check out GitHub repository ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup_environment
        with:
          cache_version: ${{ secrets.GH_ACTIONS_CACHE_KEY }}
          python-version: ${{ matrix.python-version }}
          os: ${{ matrix.os }}

      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Report coverage
        shell: bash
        run: |
          poetry run coverage combine coverage*/.coverage${{ matrix.os }}${{ matrix.python-version }}*
          poetry run coverage report
