name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub repository ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        id: py
        with:
          python-version-file: '.python-version'
          cache: 'pip'

      - name: Poetry install on Python ${{ steps.py.outputs.python-version }}
        run: |
          ${{ steps.py.outputs.python-path }} -m pip install --upgrade poetry
          ${{ steps.py.outputs.python-path }} -m poetry install --with test

      - name: Tests with Pytest
        run: PYTHONPATH=${PWD} coverage run -m pytest --verbose --durations=20 --durations-min=2.0

      - name: Report coverage
        run: coverage report

      - name: Build and Publish to Test PyPI
        uses: JRubics/poetry-publish@v1.16
        with:
          python_version: ${{ steps.py.outputs.python-version }}
          pypi_token: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"
          build_format: "wheel"
          ignore_dev_requirements: "yes"

      - name: Build and Publish to PyPI
        uses: JRubics/poetry-publish@v1.16
        with:
          python_version: ${{ steps.py.outputs.python-version }}
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
          build_format: "wheel"
          ignore_dev_requirements: "yes"
