name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10.4"]

    steps:
    - name: Check out GitHub repository ${{ github.repository }}
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install -e .[dev]
        python -m pip install -U wheel twine setuptools

    - name: Format with Black
      run: python -m black ./

    - name: Lint check with Flake8
      run: python -m flake8 ./

    - name: Tests with Pytest
      run: coverage run -m pytest --verbose

    - name: Report coverage
      run: coverage report

    - name: Package and check
      run: |
        python setup.py sdist bdist_wheel
        python -m twine check dist/*

    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: false
        verbose: true

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        repository_url: https://upload.pypi.org/legacy/
        verbose: true
