name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out GitHub repository ${{ github.repository }}
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      id: py
      with:
        python-version-file: '.python-version'
        cache: 'pip'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ env.pythonLocation }}-

    - name: Editable pip install on Python ${{ steps.py.outputs.python-version }}
      run: |
        ${{ steps.py.outputs.python-path }} -m pip install --upgrade -e .[build]

    - name: Tests with Pytest
      run: PYTHONPATH=${PWD} coverage run -m pytest --verbose --capture=no

    - name: Report coverage
      run: coverage report

    - name: Package and check
      run: |
        ${{ steps.py.outputs.python-path }} -m build
        ${{ steps.py.outputs.python-path }} -m twine check dist/*

    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: false
        verbose: true

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        repository_url: https://upload.pypi.org/legacy/
        verbose: true
