name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out GitHub repository ${{ github.repository }}
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version-file: '.python-version'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
        python -m pip install -U wheel twine setuptools

    - name: Tests with Pytest
      run: coverage run -m pytest --verbose

    - name: Report coverage
      run: coverage report

    - name: Package and check
      run: |
        python setup.py sdist bdist_wheel
        python -m twine check dist/*

    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: false
        verbose: true

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        repository_url: https://upload.pypi.org/legacy/
        verbose: true
