name: Deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    environment: dev

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install -e .[dev]
        python -m pip install -U wheel twine setuptools

    - name: Fix
      run: |
        python -m black ./

    - name: Lint
      run: |
        python -m flake8 ./

    - name: Tests with Code Coverage
      run: |
        coverage run -m pytest --verbose
        coverage report

    - name: Package and check
      run: |
        python setup.py sdist bdist_wheel
        python -m twine check dist/*

    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: false
        verbose: true

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        repository_url: https://upload.pypi.org/legacy/
        verbose: true
