name: Multitest

on: workflow_dispatch

jobs:
  testing:
    strategy:
      fail-fast: false
      matrix:
        group: [1, 2, 3, 4, 5]
    runs-on: ubuntu-latest

    steps:
    - name: Check out GitHub repository ${{ github.repository }}
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version-file: '.python-version'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install -e .[dev]
        python -m pip install -U setuptools

    - name: Format with Black
      run: python -m black ./

    - name: Lint check with Flake8
      run: python -m flake8 ./

    - name: Tests with Pytest
      run: pytest --verbose --cov --splits 5 --group ${{ matrix.group }}

    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage${{ matrix.group }}
        path: .coverage

  coverage:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub repository
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install -e .[dev]
          python -m pip install -U setuptools
      - name: Download all artifacts
        uses: actions/download-artifact@v2
      - name: Report coverage
        run: |
          coverage combine coverage*/.coverage*
          coverage report --fail-under=99