name: Normietest

on: workflow_dispatch

jobs:
  testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ~/repo

    steps:
    - name: Check out GitHub repository ${{ github.repository }}
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      id: py
      with:
        python-version-file: '.python-version'
        cache: 'pip'

    - name: Install dependencies on Python ${{ steps.py.outputs.python-version }}
      run: python -m pip install --upgrade -r requirements.txt

    - name: Tests with Pytest
      run: coverage run -m pytest --verbose

    - name: Report coverage
      run: coverage report