name: Normietest

on: workflow_dispatch

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - name: Check out GitHub repository ${{ github.repository }}
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version-file: '.python-version'
        cache: 'pip'

    - name: Install dependencies
      run: python -m pip install -e .[dev]

    - name: Format with Black
      run: python -m black ./

    - name: Lint check with Flake8
      run: python -m flake8 ./
      continue-on-error: true

    - name: Tests with Pytest
      run: coverage run -m pytest --verbose

    - name: Report coverage
      run: coverage report --fail-under=99