name: Setup the Python Environment

on: workflow_call

jobs:
  setup:
    name: setup
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        group: [ 1, 2, 3, 4, 5 ]
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        python-version: [ '3.10' ]
      fail-fast: false

    steps:
      - name: Check out GitHub repository ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup_environment
        with:
          cache_version: ${{ secrets.GH_ACTIONS_CACHE_KEY }}
          python-version: ${{ matrix.python-version }}
          os: ${{ matrix.os }}
