name: Tests

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        group: [1, 2, 3, 4, 5]
        python-version: ["3.10.4"]

    steps:
    - name: Check out GitHub repository ${{ github.repository }}
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install -e .[dev]
        python -m pip install -U wheel twine setuptools

    - name: Format with Black
      run: python -m black ./

    - name: Lint check with Flake8
      run: python -m flake8 ./

    - name: Tests with Pytest
      run: pytest --verbose --cov --splits 5 --group ${{ matrix.group }}

    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage${{ matrix.group }}
        path: .coverage

    - name: Package and check
      run: |
        python setup.py sdist bdist_wheel
        python -m twine check dist/*

  coverage:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Check out GitHub repository ${{ github.repository }}
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -e .[dev]
          python -m pip install -U wheel twine setuptools

      - name: Download all artifacts
        # Downloads coverage1, coverage2, etc.
        uses: actions/download-artifact@v2

      - name: Run coverage
        run: |
          coverage combine coverage*/.coverage*
          coverage report --fail-under=99
          coverage report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          verbose: true
