name: StandardTest

on:
  push:
    branches:
      - "*" # matches every branch that doesn't contain a '/'
      - "*/*" # matches every branch containing a single '/'
      - "**" # matches every branch

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Check out GitHub repository ${{ github.repository }}
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      id: py
      with:
        python-version-file: '.python-version'

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ env.pythonLocation }}-

    - name: Install dependencies on Python ${{ steps.py.outputs.python-version }}
      run: python -m pip install --upgrade .[test]

    - name: Tests with Pytest
      run: PYTHONPATH=${PWD} coverage run -m pytest --verbose

    - name: Report coverage
      run: coverage report