name: StandardTest

on: workflow_dispatch

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub repository ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        id: py
        with:
          python-version-file: '.python-version'
          cache: 'pip'

      - name: Install dependencies on Python ${{ steps.py.outputs.python-version }}
        run: |
          ${{ steps.py.outputs.python-path }} -m pip install --upgrade wheel
          ${{ steps.py.outputs.python-path }} -m pip install --upgrade .[test]

      - name: Tests with Pytest
        run: PYTHONPATH=${PWD} coverage run -m pytest --verbose --durations=20 --durations-min=2.0

      - name: Report coverage
        run: coverage report