name: TestsWithSplit

on:
  workflow_dispatch:
  push:
    branches:
      - "*" # matches every branch that doesn't contain a '/'
      - "*/*" # matches every branch containing a single '/'
      - "**" # matches every branch

jobs:
  stage_python:
    runs-on: ubuntu-latest

    steps:
      - name: Check out GitHub repository ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Set up Python on ${{ runner.os }}
        uses: actions/setup-python@v4
        id: setup_python
        with:
          python-version-file: '.python-version'

      - name: Install and configure Poetry
        shell: bash
        run: |
          ${{ steps.setup_python.outputs.python-path }} -m pip install poetry==1.3.2
          ${{ steps.setup_python.outputs.python-path }} -m poetry config virtualenvs.in-project true

      - name: Load cached venv
        id: cached-venv
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.pythonLocation }}
            poetry.lock
          key: venv-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}

      - name: Install Dependencies
        shell: bash
        if: steps.cached-venv.outputs.cache-hit != 'true'
        run: poetry install --with test

  run_tests:
    needs: stage_python
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        group: [ 1, 2, 3, 4, 5 ]

    steps:
      - name: Check out GitHub repository ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Set up Python on ${{ runner.os }}
        uses: actions/setup-python@v4
        id: setup_python
        with:
          python-version-file: '.python-version'

      - name: Install and configure Poetry
        shell: bash
        run: |
          ${{ steps.setup_python.outputs.python-path }} -m pip install poetry==1.3.2
          ${{ steps.setup_python.outputs.python-path }} -m poetry config virtualenvs.in-project true

      - name: Load cached venv
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.pythonLocation }}
            poetry.lock
          key: venv-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}

      - name: Install Dependencies
        shell: bash
        run: poetry install --with test

      - name: Tests with Pytest
        shell: bash
        run: poetry run coverage run -m pytest --verbose --durations=20 --durations-min=2.0 --splits 5 --group ${{ matrix.group }} --splitting-algorithm least_duration ./

      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage${{ matrix.group }}
          path: .coverage

  report_coverage:
    needs: run_tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out GitHub repository ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Set up Python on ${{ runner.os }}
        uses: actions/setup-python@v4
        id: setup_python
        with:
          python-version-file: '.python-version'

      - name: Install and configure Poetry
        shell: bash
        run: |
          ${{ steps.setup_python.outputs.python-path }} -m pip install poetry==1.3.2
          ${{ steps.setup_python.outputs.python-path }} -m poetry config virtualenvs.in-project true

      - name: Load cached venv
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.pythonLocation }}
            poetry.lock
          key: venv-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}

      - name: Install Dependencies
        shell: bash
        run: poetry install --with test

      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Report coverage
        shell: bash
        run: |
          poetry run coverage combine coverage*/.coverage*
          poetry run coverage report
