name: TestsWithSplit

on:
  workflow_dispatch:
  push:
    branches:
      - "*" # matches every branch that doesn't contain a '/'
      - "*/*" # matches every branch containing a single '/'
      - "**" # matches every branch

env:
  POETRY_VER: 1.3.2

jobs:
  stage_python:
    runs-on: ubuntu-latest

    steps:
      - name: Check out GitHub repository ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Set up Python on ${{ runner.os }}
        uses: actions/setup-python@v4
        id: setup_python
        with:
          python-version-file: '.python-version'

      - name: Cache Poetry
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: .venv
          key: poetry-${{ env.POETRY_VER }}-${{ hashFiles('**/poetry.toml') }}

      - name: Install Poetry ${{ env.POETRY_VER }}
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VER }}
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: .venv
          key: pydeps-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}

      - name: Install Dependencies on Python ${{ steps.setup_python.outputs.python-version }}
        shell: bash
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: poetry install --no-root --with test

  run_tests:
    needs: stage_python
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        group: [ 1, 2, 3, 4, 5 ]

    steps:
      - name: Check out GitHub repository ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Set up Python on ${{ runner.os }}
        uses: actions/setup-python@v4
        id: setup_python
        with:
          python-version-file: '.python-version'

      - name: Cache Poetry
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: .venv
          key: poetry-${{ env.POETRY_VER }}-${{ hashFiles('**/poetry.toml') }}

      - name: Install Poetry ${{ env.POETRY_VER }}
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VER }}
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: .venv
          key: pydeps-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}

      - name: Install Dependencies on Python ${{ steps.setup_python.outputs.python-version }}
        shell: bash
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: poetry install --no-root --with test

      - name: Tests with Pytest
        shell: bash
        run: coverage run -m pytest --verbose --durations=20 --durations-min=2.0 --splits 5 --group ${{ matrix.group }} --splitting-algorithm least_duration ./

      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage${{ matrix.group }}
          path: .coverage

  report_coverage:
    needs: run_tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out GitHub repository ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Set up Python on ${{ runner.os }}
        uses: actions/setup-python@v4
        id: setup_python
        with:
          python-version-file: '.python-version'

      - name: Cache Poetry
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: .venv
          key: poetry-${{ env.POETRY_VER }}-${{ hashFiles('**/poetry.toml') }}

      - name: Install Poetry ${{ env.POETRY_VER }}
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VER }}
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: .venv
          key: pydeps-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}

      - name: Install Dependencies on Python ${{ steps.setup_python.outputs.python-version }}
        shell: bash
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: poetry install --no-root --with test

      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Report coverage
        shell: bash
        run: |
          coverage combine coverage*/.coverage*
          coverage report
