name: tests

on:
  workflow_dispatch:
  push:
    branches:
      - "*" # matches every branch that doesn't contain a '/'
      - "*/*" # matches every branch containing a single '/'
      - "**" # matches every branch

env:
  POETRY_VER: 1.7.1

jobs:
  run_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out GitHub repository ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Set up Python on ${{ runner.os }}
        uses: actions/setup-python@v4
        id: setup_python
        with:
          python-version: '3.12'

      - name: Update pip
        run: pip install --upgrade pip

      - name: Install Poetry ${{ env.POETRY_VER }} on Python ${{ steps.setup_python.outputs.python-version }}
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ env.POETRY_VER }}

      - name: Install dependencies on Python ${{ steps.setup_python.outputs.python-version }}
        run: poetry install --with dev

      - name: Tests with Pytest
        run: poetry run coverage run -m pytest --verbose --capture=no

      - name: Report coverage
        run: poetry run coverage report -m
