name: TestsWithSplit

on:
  workflow_dispatch:
  push:
    branches:
      - "*" # matches every branch that doesn't contain a '/'
      - "*/*" # matches every branch containing a single '/'
      - "**" # matches every branch

env:
  POETRY_VER: 1.3.2

jobs:
  stage_python:
    runs-on: ubuntu-latest

    steps:
      - name: Check out GitHub repository ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Set up Python on ${{ runner.os }}
        uses: actions/setup-python@v4
        id: setup_python
        with:
          python-version-file: '.python-version'

      - name: Load cached venv
        id: cached_venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install and configure Poetry ${{ env.POETRY_VER }}
        run: |
          curl -O -sSL https://install.python-poetry.org/install-poetry.py
          python install-poetry.py -y --version ${{ env.POETRY_VER }}
          echo "PATH=${HOME}/.poetry/bin:${PATH}" >> $GITHUB_ENV
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
          poetry config virtualenvs.options.no-pip true
          poetry config virtualenvs.options.no-setuptools true
          poetry env use ${{ steps.setup_python.outputs.python-version }}
          rm install-poetry.py
        if: steps.cached_venv.outputs.cache-hit != 'true'

      - name: Install Dependencies on Python ${{ steps.setup_python.outputs.python-version }}
        run: |
          poetry install  --no-root --with test
        if: steps.cached_venv.outputs.cache-hit != 'true'

  run_tests:
    needs: stage_python
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        group: [ 1, 2, 3, 4, 5 ]

    steps:
      - name: Check out GitHub repository ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Set up Python on ${{ runner.os }}
        uses: actions/setup-python@v4
        id: setup_python
        with:
          python-version-file: '.python-version'

      - name: Load cached venv
        id: cached_venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install and configure Poetry ${{ env.POETRY_VER }}
        run: |
          curl -O -sSL https://install.python-poetry.org/install-poetry.py
          python install-poetry.py -y --version ${{ env.POETRY_VER }}
          echo "PATH=${HOME}/.poetry/bin:${PATH}" >> $GITHUB_ENV
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
          poetry config virtualenvs.options.no-pip true
          poetry config virtualenvs.options.no-setuptools true
          poetry env use ${{ steps.setup_python.outputs.python-version }}
          rm install-poetry.py
        if: steps.cached_venv.outputs.cache-hit != 'true'

      - name: Install Dependencies on Python ${{ steps.setup_python.outputs.python-version }}
        run: |
          poetry install  --no-root --with test
        if: steps.cached_venv.outputs.cache-hit != 'true'

      - name: Tests with Pytest
        shell: bash
        run: poetry run coverage run -m pytest --verbose --durations=20 --durations-min=2.0 --splits 5 --group ${{ matrix.group }} --splitting-algorithm least_duration ./

      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage${{ matrix.group }}
          path: .coverage

  report_coverage:
    needs: run_tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out GitHub repository ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Set up Python on ${{ runner.os }}
        uses: actions/setup-python@v4
        id: setup_python
        with:
          python-version-file: '.python-version'

      - name: Load cached venv
        id: cached_venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install and configure Poetry ${{ env.POETRY_VER }}
        run: |
          curl -O -sSL https://install.python-poetry.org/install-poetry.py
          python install-poetry.py -y --version ${{ env.POETRY_VER }}
          echo "PATH=${HOME}/.poetry/bin:${PATH}" >> $GITHUB_ENV
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
          poetry config virtualenvs.options.no-pip true
          poetry config virtualenvs.options.no-setuptools true
          poetry env use ${{ steps.setup_python.outputs.python-version }}
          rm install-poetry.py
        if: steps.cached_venv.outputs.cache-hit != 'true'

      - name: Install Dependencies on Python ${{ steps.setup_python.outputs.python-version }}
        run: |
          poetry install  --no-root --with test
        if: steps.cached_venv.outputs.cache-hit != 'true'

      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Report coverage
        shell: bash
        run: |
          poetry run coverage combine coverage*/.coverage*
          poetry run coverage report
