name: Test & report coverage

on:
  workflow_dispatch:
  workflow_call:

jobs:
  unittest:
    name: unittest
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        python-version: [ '3.10' ]
      fail-fast: false

    steps:
      - name: Tests with Pytest
        run: poetry run coverage run -m pytest --verbose --durations=20 --durations-min=2.0

      - name: Report coverage
        run: poetry run coverage report
