name: Unit Test & Upload Coverage

on:
  workflow_dispatch:
  workflow_call:

jobs:
  unittest:
    name: unittest
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        group: [ 1, 2, 3, 4, 5 ]
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        python-version: [ '3.10' ]
      fail-fast: false

    steps:
      - name: Check out GitHub repository ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup_environment
        with:
          cache_version: ${{ secrets.GH_ACTIONS_CACHE_KEY }}
          python-version: ${{ matrix.python-version }}
          os: ${{ matrix.os }}

      - name: Tests with Pytest
        shell: bash
        run: poetry run coverage run -m pytest --verbose --durations=20 --durations-min=2.0 --splits 5 --group ${{ matrix.group }} --data-file=coverage${{ matrix.group }} --splitting-algorithm least_duration ./

      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage${{ matrix.group }}
          path: .coverage${{ matrix.os }}${{ matrix.python-version }}
